version: "3.7"
services:
  dto:
    container_name: dto
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      args:
        USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www/html/
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
